### ISSUE TITLE
Add filter for ignoring certain endpoints

### ISSUE THREAD

**Issue by Azuka** [riandyrn/otelchi#10]
Thanks for this project: I've been using it for a couple months now.

Would it be possible to ignore a healthcheck endpoint due to the frequency of calls?

Elsewhere it seems the pattern is to accept function filters that return a boolean: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/896

I'd be happy to open a pull request if you think the idea has merit.

**Comment by riandyrn** [comment]
Hello, @Azuka

Yeah, I think this would be great.

Looking forward to your PR.

**Comment by hsblhsn** [comment]
Hey @Azuka,
Is there any update on that? If no, I can open one 😄 

Thanks 🙏
