### ISSUE TITLE
panic doesn't mark span as error

### ISSUE THREAD

**Issue by aep** [riandyrn/otelchi#12]
the middleware doesn't call recover anywhere, pressumably because otel already does that according to the trace

```
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
	/home/aep/.go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.11.0/trace/span.go:396 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc00033e480, {0x0, 0x0, 0xc0000b4780?})
	/home/aep/.go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.11.0/trace/span.go:435 +0x8ee
```

this records an event, but does not set the span as error.

confusingly, a 404 is set as error,  ~~but i don't understand where that's happening either.~~   because otelchi calls span.SetStatus . should it also do that for panic, or is that a problem in otel?

**Comment by aep** [comment]
https://github.com/open-telemetry/opentelemetry-go/issues/3283

**Comment by riandyrn** [comment]
Closed based on https://github.com/riandyrn/otelchi/pull/13#issuecomment-1374393645.
