### ISSUE TITLE
Metric support

### ISSUE THREAD

**Issue by jlordiales** [riandyrn/otelchi#20]
Hi there!

Would you be interested in adding optional support for some basic metrics? I'm thinking a single histogram to track request latency tagged with http method, route and response code.

Since Histograms also provide a `count` metric that should be enough to build your typical RED dashboard.

Happy to submit a PR for it!

**Comment by MDr164** [comment]
I can support that to some degree. I would be very interested in that feature but I currently have it somewhat lower on my priority list. But I'm happy to review and test any open PRs here. If no PR shows up within the next months I'll tackle that issue myself once it moved up the list :)

**Comment by ilhamsyahids** [comment]
Support metrics on [v0.11.0](https://github.com/riandyrn/otelchi/releases/tag/v0.11.0)
