### ISSUE TITLE
Empty status code in span when handler is not sending data

### ISSUE THREAD

**Issue by ajdevries** [riandyrn/otelchi#26]
If you create a HTTP Handler that is not writing anything and not setting the status code (`WriteHeader`) the status in the span is `0`. The HTTP Server returns a `200` is this expected? It is because the status value is set to `0` as an initial value.

- https://github.com/riandyrn/otelchi/blob/master/middleware.go#L78

I can create a PR that changes this to `200`?

**Comment by riandyrn** [comment]
Hey, @ajdevries

Yeah, you are correct. It's a bug.

Feel free to create the PR. 👍🏻

**Comment by ajdevries** [comment]
@riandyrn thanks for the quick reply, PR is [here](https://github.com/riandyrn/otelchi/pull/30)
