### ISSUE TITLE
Add Real-World Usage Example for Metric Feature

### ISSUE THREAD

**Issue by riandyrn** [riandyrn/otelchi#79]
Currently, there is no example demonstrating the real-world usage of the metric feature, which is crucial for helping first-time users understand and implement it effectively.

**Proposal:**

Add an example of the metric feature in the [multi-services example directory](https://github.com/riandyrn/otelchi/tree/master/examples/multi-services). The example should use a real metric collector such as Prometheus to showcase its functionality.

This addition would greatly enhance the usability of the metric feature for new users.

**Comment by fathiraz** [comment]
Hey mas ryan, thank you for developed this great library.

I just saw your chat about adding a real-world example for the metric feature in our wagroup. That will really help peoples for easier integration on this metric.

I sent up a PR that should be cover on this issue! Check it out [here](https://github.com/riandyrn/otelchi/pull/83) 💻 

It is include an example with Prometheus, just like you requested. Would love to hear your opinion on it 🔥

**Comment by riandyrn** [comment]
Hello, @fathiraz

Thanks for your contribution! 😁🎉

Btw, it looks like you have some comments from @ilhamsyahids in the PR. He is one of the core maintainers of this library. So please work on it. 👍🏻
