### ISSUE TITLE
docker-compose is deprecated

### ISSUE THREAD

**Issue by Hidayathamir** [riandyrn/otelchi#80]
`docker-compose` is deprecated. Should use `docker compose` which is the `v2` of `docker-compose`.

[SO docker-compose vs docker compose](https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose#comment127881538_66516826)

> From July 2023 Compose V1 stopped receiving updates
[Migrate to Compose V2](https://docs.docker.com/compose/releases/migrate/)

When I try to run [`make run`](https://github.com/riandyrn/otelchi/blob/master/examples/multi-services/Makefile#L1) I got this error.

```
docker-compose down --remove-orphans
make[1]: docker-compose: No such file or directory
```

I can solve it by installing `docker-compose`, but I think it's good if the Makefile is using the `v2`.

What do you think? should we update all the Makefile to use `docker compose`?

**Comment by riandyrn** [comment]
Hello, @Hidayathamir

Nice catch!

> What do you think? should we update all the Makefile to use docker compose?

Sure, can you create a PR for it?

**Comment by ilhamsyahids** [comment]
I remember we use docker-compose because github action doesn't support v2. But it might support right now
